# Generated by Django 5.1 on 2024-08-31 17:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Status', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Libros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Titulo')),
                ('autor', models.CharField(max_length=50, verbose_name='Autor')),
                ('fecha_publicacion', models.DateTimeField(verbose_name='Fecha Publicacion')),
                ('genero', models.CharField(max_length=30, verbose_name='Genero')),
                ('idStatus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Status.status')),
            ],
        ),
    ]
